[package]
name = "imstr"
version = "0.1.0"
edition = "2021"
description = "Cheaply clonable and slicable immutable strings"
documentation = "https://docs.rs/imstr"
repository = "https://github.com/xfbs/imstr"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
license = "MIT"

[dependencies]
serde = { version = "1.0.159", optional = true }

[features]
default = ["std"]
serde = ["dep:serde"]
std = []
alloc = []
